"""Added sotred_at to Weather table

Revision ID: adfde2a9b45a
Revises: e545beb57864
Create Date: 2026-02-01 12:14:27.882452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfde2a9b45a'
down_revision = 'e545beb57864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_column('stored_at')

    # ### end Alembic commands ###
