"""Added indexes to created_at and stored_at

Revision ID: c45405b8bd0e
Revises: b77adb728b13
Create Date: 2026-02-03 22:19:20.327284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45405b8bd0e'
down_revision = 'b77adb728b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_stored_at'), ['stored_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_stored_at'))
        batch_op.drop_index(batch_op.f('ix_weather_created_at'))

    # ### end Alembic commands ###
