"""neon.tech

Revision ID: de5d75562d84
Revises: 
Create Date: 2026-02-04 20:51:47.897754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de5d75562d84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('light', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_stored_at'), ['stored_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_stored_at'))
        batch_op.drop_index(batch_op.f('ix_weather_created_at'))

    op.drop_table('weather')
    # ### end Alembic commands ###
